### ISSUE TITLE
Unable to spawn actor: car1

### ISSUE THREAD

**Issue by eerkaijun** [praveen-palanisamy/macad-gym#34]
When running `env.reset()`, I encounter the following error: 

```
reset(): Retry #: 1/2
Clearing Carla server state
RuntimeError: Unable to spawn actor:car1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/inf.ed.ac.uk/group/ug4-projects/s1800883/Carla/env/lib/python3.7/site-packages/macad_gym/carla/multi_env.py", line 590, in reset
    raise error
  File "/afs/inf.ed.ac.uk/group/ug4-projects/s1800883/Carla/env/lib/python3.7/site-packages/macad_gym/carla/multi_env.py", line 583, in reset
    return self._reset()
  File "/afs/inf.ed.ac.uk/group/ug4-projects/s1800883/Carla/env/lib/python3.7/site-packages/macad_gym/carla/multi_env.py", line 774, in _reset
    "Unable to spawn actor:{}".format(actor_id))
  File "/afs/inf.ed.ac.uk/group/ug4-projects/s1800883/Carla/env/lib/python3.7/site-packages/macad_gym/carla/multi_env.py", line 768, in _reset
    self._actors[actor_id] = self._spawn_new_agent(actor_id)
  File "/afs/inf.ed.ac.uk/group/ug4-projects/s1800883/Carla/env/lib/python3.7/site-packages/macad_gym/carla/multi_env.py", line 683, in _spawn_new_agent
    self.world.wait_for_tick()
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:49821
```

I'm using the following specs: 
Python version: 3.7.3
CARLA: 0.9.11
OS: Ubuntu 20.04

**Comment by praveen-palanisamy** [comment]
Hi @eerkaijun,
From the error log, it looks like the CARLA server process is failing to start after couple of retries. 
Just to be sure, have you installed all the system requirements and setup including the `CARLA_SERVER` environment variable as mentioned in the [Getting started](https://github.com/praveen-palanisamy/macad-gym#getting-started) section?

**Comment by eerkaijun** [comment]
Yes, I've done that. I could also see my carla server running, however the client seems unable to connect to it. As I am using carla 0.9.11 (instead of the one specified 0.9.4), is that one possible reason for the client not to be able to connect?

**Comment by praveen-palanisamy** [comment]
Yes, please use `0.9.4`. The server checks for the client's version and `0.9.11` does have some incompatible changes.

**Comment by eerkaijun** [comment]
Your suggestion works! Thanks for the help!
