### ISSUE TITLE
env._seed issue

### ISSUE THREAD

**Issue by mapestar** [praveen-palanisamy/macad-gym#4]
hello!

i just copy your basic agent-environment interaction loop and run it(test.py), and error below has happened.

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    env = gym.make("HomoNcomIndePOIntrxMASS3CTWN3-v0")
  File "/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py", line 163, in make
    return registry.make(id)
  File "/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py", line 121, in make
    patch_deprecated_methods(env)
  File "/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py", line 181, in patch_deprecated_methods
    env.seed  = env._seed
AttributeError: 'TrafficLightSignal1B2C1PTown03' object has no attribute '_seed'

with "HeteNcomIndePOIntrxMATLS1B2C1PTWN3-v0" scenario.

can you help me with this?

**Comment by mapestar** [comment]
with developers' code, i did it
