### ISSUE TITLE
Running examle code

### ISSUE THREAD

**Issue by Yiquan-lol** [praveen-palanisamy/macad-gym#40]
Hi,

I am trying to run the example code basci agents.py, and I get the following error:
Traceback (most recent call last):
  File "basic_agent.py", line 5, in <module>
    env = gym.make("HomoNcomIndePOIntrxMASS3CTWN3-v0")
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/gym/envs/registration.py", line 125, in make
    env = spec.make(**kwargs)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/gym/envs/registration.py", line 88, in make
    cls = load(self._entry_point)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/gym/envs/registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/software/macad-gym/src/macad_gym/envs/__init__.py", line 1, in <module>
    from macad_gym.carla.multi_env import MultiCarlaEnv
  File "/home/user/software/macad-gym/src/macad_gym/carla/multi_env.py", line 220, in <module>
    from ray.rllib.env import MultiAgentEnv
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/__init__.py", line 11, in <module>
    from ray.rllib.evaluation.policy_graph import PolicyGraph
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/evaluation/__init__.py", line 2, in <module>
    from ray.rllib.evaluation.policy_evaluator import PolicyEvaluator
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 18, in <module>
    from ray.rllib.evaluation.sampler import AsyncSampler, SyncSampler
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 14, in <module>
    from ray.rllib.evaluation.tf_policy_graph import TFPolicyGraph
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/evaluation/tf_policy_graph.py", line 12, in <module>
    from ray.rllib.models.lstm import chop_into_sequences
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/models/__init__.py", line 1, in <module>
    from ray.rllib.models.catalog import ModelCatalog, MODEL_DEFAULTS
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/models/catalog.py", line 17, in <module>
    from ray.rllib.models.fcnet import FullyConnectedNetwork
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/ray/rllib/models/fcnet.py", line 6, in <module>
    import tensorflow.contrib.slim as slim
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/__init__.py", line 28, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 33, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnCompatibleGRUCell
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 21, in <module>
    from tensorflow.contrib.rnn.python.ops import lstm_ops
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/rnn/__init__.py", line 83, in <module>
    from tensorflow.contrib.rnn.python.ops.gru_ops import *
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/gru_ops.py", line 33, in <module>
    resource_loader.get_path_to_datafile("_gru_ops.so"))
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/user/anaconda3/envs/macad-gym/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not parse default value '4000' from Attr("upper_frequency_limit: float = 4000") for Op Mfcc
Could not parse default value '20' from Attr("lower_frequency_limit: float = 20") for Op Mfcc
Killing live carla processes set()

Carla is not running, What is the matter, please

**Comment by praveen-palanisamy** [comment]
Hi @Yiquan-lol ,
This is likely related to #27. To confirm, could you add the python package versions you are using in your env?
You can run this command: `pip freeze > packages.txt` and upload the `packages.txt` in your reply.

**Comment by Yiquan-lol** [comment]
[package.txt](https://github.com/praveen-palanisamy/macad-gym/files/6505632/package.txt)
I created the environment from the conda-env.yml file

**Comment by praveen-palanisamy** [comment]
@Yiquan-lol : Thanks for the python environment info.
I am unfortunately not able to reproduce this error. Could you please try again with this line: 
`import tensorflow` 
added after this line:
https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/carla/multi_env.py#L219

and report back if your issues is solved/not-solved?:

**Comment by Yiquan-lol** [comment]
Thank you. I did it according to your method, but the result is still the same.
I wonder if it's the TensorFlow version that's causing the problem

**Comment by Yiquan-lol** [comment]
Oh , I followed the same steps to reinstall the Conda environment and basci agent.py is running.Thank you for your previous help

**Comment by Yiquan-lol** [comment]
I found a problem: after setting up the macad-gym environment, I could run basic-agent.py, but the 'import tensorflow' would tell me that I was missing the cudatoolkit file.
When I used 'conda install cudatoolkit==8.0 condainstall cudnn', I failed to run basic_agent.py and had the same problem as before.

**Comment by praveen-palanisamy** [comment]
Thank you for the follow-on and updates!
Could you post the full error log? That'll help to see what's going wrong.

**Comment by Yiquan-lol** [comment]
After installing the MacAd-Gym environment, you can run basic_agent.py.When running "import tensorflow", "error_1" appears.
[error_1.txt](https://github.com/praveen-palanisamy/macad-gym/files/6512312/error_1.txt)
After I install the cudatoolkit and cudnn, run "basic_anent" and "error_2" will appear.
[error_2.txt](https://github.com/praveen-palanisamy/macad-gym/files/6512313/error_2.txt)
Can you use TensorFlow directly after installing the MacAd-Gym environment?
Did you install cudatoolkit and cudnn via "conda install"?

**Comment by Yiquan-lol** [comment]
> 感谢您的后续和更新！
> 您可以发布完整的错误日志吗？这将有助于了解问题所在。

`import tensorflow`

**Comment by praveen-palanisamy** [comment]
Thanks for the logs with clear explanation!
1. After you installed `cudatoolkit==8.0`, did you try adding the `import tensorflow` to that particular line in that file as mentioned here: https://github.com/praveen-palanisamy/macad-gym/issues/40#issuecomment-843780537 ?

2. > Can you use TensorFlow directly after installing the MacAd-Gym environment? 
  
   Yes. In case this detail helps, I have `cuda-8.0` on my system and the following commands sets up the required env vars:
   - `export PATH="$PATH:/usr/local/cuda-8.0/bin"`
   - `export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64"`
3. > Did you install cudatoolkit and cudnn via "conda install"?
     
      No

**Comment by Yiquan-lol** [comment]
I did what you told me, but I still made the same error

**Comment by Yiquan-lol** [comment]
I did what you told me, but I still made the same error.
Can I change the tensorFlow version in conda_env.yml and reinstall the macad-yym environment to accommodate the CUDA version of my system?

**Comment by Yiquan-lol** [comment]
> Thanks for the logs with clear explanation!
> 
> 1. After you installed `cudatoolkit==8.0`, did you try adding the `import tensorflow` to that particular line in that file as mentioned here: [#40 (comment)](https://github.com/praveen-palanisamy/macad-gym/issues/40#issuecomment-843780537) ?
> 2. > Can you use TensorFlow directly after installing the MacAd-Gym environment?
>    
>    
>    Yes. In case this detail helps, I have `cuda-8.0` on my system and the following commands sets up the required env vars:
>    
>    * `export PATH="$PATH:/usr/local/cuda-8.0/bin"`
>    * `export LD_LIBRARY_PATH="/usr/local/cuda-8.0/lib64"`
> 3. > Did you install cudatoolkit and cudnn via "conda install"?
>    
>    
>    No

I used the conda directive to install the same version of TensorFlow as yours：
`conda install tensorflow-gpu==1.4.1`
When I run basic agent.py again, I get a new error：
[error_3.txt](https://github.com/praveen-palanisamy/macad-gym/files/6517035/error_3.txt)
I don't know what's going on here

**Comment by Yiquan-lol** [comment]
I used the conda directive to install the same version of TensorFlow as yours：
`conda install tensorflow-gpu==1.4.1`
When I run basic agent.py again, I get a new error：
[error_3.txt](https://github.com/praveen-palanisamy/macad-gym/files/6517046/error_3.txt)
I don't know what's going on here

**Comment by praveen-palanisamy** [comment]
@Yiquan-lol , did you happen to get this issue resolved?
It doesn't seem to be easily reproducible and your error log points to some issues at the cpython/symbol level, specific to the GNU libc on your system and the CARLA wheel built using cpython.

**Comment by Yiquan-lol** [comment]
Oh, that's too bad.
I see that your Conda environment has Torch, so maybe I can use PyTorch for training.
Thank you for your help.

**Comment by praveen-palanisamy** [comment]
@Yiquan-lol , if you are unblocked, can this issue be closed?
