### ISSUE TITLE
Multiprocess pickle Problem

### ISSUE THREAD

**Issue by Panshark** [praveen-palanisamy/macad-gym#58]
Hi @praveen-palanisamy ,

I want to use multiprocess in macad-gym, but I find pygame cannot be pickled:
```

Cleaned-up the world...
Clearing Carla server state
/gym/gym/wrappers/monitor.py:31: UserWarning: The Monitor wrapper is being deprecated in favor of gym.wrappers.RecordVideo and gym.wrappers.RecordEpisodeStatistics (see https://github.com/openai/gym/issues/2297)
  warnings.warn(
Traceback (most recent call last):
  File "/driving_meta_0.9/train.py", line 145, in <module>
    main(args)
  File "/driving_meta_0.9/train.py", line 59, in main
    sampler = MultiTaskSampler(config['env-name'],
  File "/driving_meta_0.9/maml_rl/samplers/multi_task_sampler.py", line 107, in __init__
    worker.start()
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/multiprocess/reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 498, in dump
    StockPickler.dump(self, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 931, in save_list
    self._batch_appends(obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 958, in _batch_appends
    save(tmp[0])
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/anaconda3/envs/driving/lib/python3.8/site-packages/dill/_dill.py", line 990, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/anaconda3/envs/driving/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'pygame.font.Font' object
Killing live carla processes set()
```

Can we use something to replace pygame? I notice you use it to obtain observation. Or do you have any idea how to pickle it?

Really thank you very much.

**Comment by praveen-palanisamy** [comment]
Hi @Panshark , apologies for the delayed response. Unfortunately, pygame objects cannot be pickled. Any replacement for pygame (to render/display to screen) will also likely use objects that cannot be pickled.
Could you explain your use case and use of `multiprocessing`? There is likely other ways to achieve the parallelization/multiprocessing you are looking for.

**Comment by Panshark** [comment]
Hi @praveen-palanisamy ,

In the beginning, I tried to train a meta reinforcement learning network for Carla, so I need to use `multiprocessing` to due with the inner sampling of meta-rl. However, since I am questioning whether meta could work in such a complex task as autonomous driving or not, I did not continue to experiment on the Meta network. If you have any information about this idea, please tell me, really thank you.

Now I am trying to design some continuous changing environment in Carla, do you have any example of how do we define the weather changing using cloudy, precipitation, precipitation deposits, and wind intensity? Like, give it a changing function to simulate the weather change in our true world. Also, I will be really grateful if you can share any information about this question.

Best Regards

**Comment by praveen-palanisamy** [comment]
Hi @Panshark ,
Thank you for explaining your use case.
You can randomize the weather in each of the training episode by customizing the `"weather_distribution"` config in the scenario definition for example, you could change this line:
https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/carla/scenarios.py#L113
to include multiple weather conditions like this: 
`"weather_distribution": [0, 1, 2, 3, 4],`
Where the weather integer enum values are described as below:
https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/carla/scenarios.py#L8-L23

If you want to change the weather dynamically within each of the episodes (not recommended), you can use the CARLA API directly. Sample script to dynamically change weather is provided here: [Dynamic Weather](https://github.com/praveen-palanisamy/macad-gym/blob/38884ac4bc7fb2e91a865950cff4eeadeed02f60/src/macad_gym/carla/PythonAPI/dynamic_weather.py)

Converting this question to a GitHub discussion. Mark as answered if you got answer to your question.
